jobs:
  - name: allpl_manifestN11
    type: manifest
    steps:
      - IN: spogtest1 
      - IN: triggertestS1sreya
      - TASK: managed
      
  - name: runSHTIME
    type: runSh
  #  serial: true
    steps:
      - IN: reporun
     # - IN: ar-testtime
     # - IN:r123env
      - IN: triggertestS1sreya
      - TASK:
        - script: ./IN/reporun/gitRepo/echo.sh
